DARKNET_EMBEDDED_VERSION = v1.3
DARKNET_EMBEDDED_SITE = https://github.com/johnosbb/darknet_embedded/archive/refs/tags
DARKNET_EMBEDDED_SOURCE = $(DARKNET_EMBEDDED_VERSION).tar.gz
DARKNET_EMBEDDED_LICENSE = MIT
DARKNET_EMBEDDED_LICENSE_FILES = LICENSE
DARKNET_EMBEDDED_CONF_OPTS = -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release
DARKNET_EMBEDDED_INSTALL_STAGING = YES
ifeq ($(BR2_TOOLCHAIN_USES_UCLIBC),y)
DARKNET_EMBEDDED_CFLAGS += -DUSE_UCLIBC=ON
endif

ifeq ($(BR2_TOOLCHAIN_USES_GLIBC),y)
DARKNET_EMBEDDED_CFLAGS += -DUSE_GLIBC=ON
endif

ifeq ($(BR2_TOOLCHAIN_USES_MUSL),y)
DARKNET_EMBEDDED_CFLAGS += -DUSE_MUSL=ON
endif

DARKNET_EMBEDDED_CONF_OPTS = $(DARKNET_EMBEDDED_CFLAGS)




define DARKNET_EMBEDDED_BUILD_CMDS
    $(MAKE) -C $(@D)
endef
$(eval $(cmake-package))
$(eval $(host-cmake-package))




